package org.streeto.ui.preferences

import tornadofx.*

class PreferencesViewModel : ItemViewModel<ObservablePreferences>() {

    val routeChoiceWeighting = bind(ObservablePreferences::routeChoiceWeightingProperty)
    val legLengthWeighting = bind(ObservablePreferences::legLengthWeightingProperty)
    val legComplexityWeighting = bind(ObservablePreferences::legComplexityWeightingProperty)
    val beenHereBeforeWeighting = bind(ObservablePreferences::beenHereBeforeWeightingProperty)
    val comesTooCloseWeighting = bind(ObservablePreferences::comesTooCloseWeightingProperty)
    val dogLegWeighting = bind(ObservablePreferences::dogLegWeightingProperty)
    val distinctControlSiteWeighting = bind(ObservablePreferences::distinctControlSiteWeightingProperty)
    val maxExecutionTime = bind(ObservablePreferences::maxExecutionTimeProperty)
    val maxGenerations = bind(ObservablePreferences::maxGenerationsProperty)
    val stoppingFitness = bind(ObservablePreferences::stoppingFitnessProperty)
    val controlSwapProbability = bind(ObservablePreferences::controlSwapProbabilityProperty)
    val mutateProbability = bind(ObservablePreferences::mutateProbabilityProperty)
    val maxFirstLegLength = bind(ObservablePreferences::maxFirstControlDistanceProperty)
    val maxLastLegLength = bind(ObservablePreferences::maxLastLegLengthProperty)
    val minLegDistance = bind(ObservablePreferences::minLegDistanceProperty)
    val maxLegDistance = bind(ObservablePreferences::maxLegDistanceProperty)
    val minControlSeparation = bind(ObservablePreferences::minControlSeparationProperty)
    val turnDensity = bind(ObservablePreferences::turnDensityProperty)
    val allowedCourseLengthDelta = bind(ObservablePreferences::allowedCourseLengthDeltaProperty)
    val maxMapScale = bind(ObservablePreferences::maxMapScaleProperty)
    val minApproachToFinish = bind(ObservablePreferences::minApproachToFinishProperty)
    val offspringFraction = bind(ObservablePreferences::offspringFractionProperty)
    val populationSize = bind(ObservablePreferences::populationSizeProperty)
    val mutationRadius = bind(ObservablePreferences::mutationRadiusProperty)
    val maxPhenotypeAge = bind(ObservablePreferences::maxPhenotypeAgeProperty)
    val maxRouteShare = bind(ObservablePreferences::maxRouteShareProperty)
    val csimCellSize = bind(ObservablePreferences::csimCellSizeProperty)
    val maxFurnitureDistance = bind(ObservablePreferences::maxFurnitureDistanceProperty)
    val junctionScoreFactor = bind(ObservablePreferences::junctionScoreFactorProperty)
    val bendScoreFactor = bind(ObservablePreferences::bendScoreFactorProperty)
    val minTurnAngle = bind(ObservablePreferences::minTurnAngleProperty)
    val splitForBetterScale = bind(ObservablePreferences::splitForBetterScaleProperty)
    val mapStyle = bind(ObservablePreferences::mapStyleProperty)
    val paperSize = bind(ObservablePreferences::paperSizeProperty)
    val printA3OnA4 = bind(ObservablePreferences::printA3OnA4Property)
    val avgLegDistance = bind(ObservablePreferences::avgLegDistanceProperty)
}