package org.streeto.ui

interface IPreferenceConstants {
    companion object {
        const val STREETO_CONSTRAINTS_MAXFINISHLEN = "streeto.constraints.maxfinishlen"
        const val STREETO_CONSTRAINTS_MAXFIRSTLEN = "streeto.constraints.maxfirstlen"
        const val STREETO_CONSTRAINTS_MINAPPROACHFINISH = "streeto.constraints.minapproachfinish"
        const val STREETO_CONSTRAINTS_MINLEGLEN = "streeto.constraints.minleglen"
        const val STREETO_CONSTRAINTS_MAXLEGLEN = "streeto.constraints.maxleglen"
        const val STREETO_CONSTRAINTS_MAXLENDELTA = "streeto.constraints.maxlendelta"
        const val STREETO_CONSTRAINTS_MUTATION_RADIUS = "streeto.constraints.mutation.radius"
        const val STREETO_CONSTRAINTS_MAXROUTESHARE = "streeto.constraints.maxrouteshare"
        const val STREETO_CONSTRAINTS_MAXFURNITUREDIST = "streeto.constraints.maxfurnituredist"
        const val STREETO_CONSTRAINTS_MINBENDANGLE = "streeto.constraints.minbendangle"
        const val STREETO_WEIGHTS_ROUTECHOICE = "streeto.weights.routechoice"
        const val STREETO_WEIGHTS_LENGTH = "streeto.weights.length"
        const val STREETO_WEIGHTS_DOGLEG = "streeto.weights.dogleg"
        const val STREETO_WEIGHTS_COMPLEXITY = "streeto.weights.complexity"
        const val STREETO_WEIGHTS_COMINGBACKHERE = "streeto.weights.comingbackhere"
        const val STREETO_WEIGHTS_BEENHEREBEFORE = "streeto.weights.beenherebefore"
        const val STREETO_WEIGHTS_DISTINCTCONTROL = "streeto.weights.distinctcontrol"
        const val STREETO_MAP_MAXSCALE = "streeto.map.maxscale"
        const val STREETO_MAP_ALLOWSPLIT = "streeto.map.allowsplit"
        const val STREETO_MAP_USEA3 = "streeto.map.usea3"
        const val STREETO_MAP_PRINT_A3_ON_A4 = "streeto.map.printa3ona4"
        const val STREETO_MAP_STYLE = "streeto.map.style"
        const val STREETO_JENETICS_SWAPPROBABILITY = "streeto.jenetics.swapprobability"
        const val STREETO_JENETICS_MUTATEPROBABILITY = "streeto.jenetics.mutateprobability"
        const val STREETO_JENETICS_MAXTIME = "streeto.jenetics.maxtime"
        const val STREETO_JENETICS_MAXGENERATIONS = "streeto.jenetics.maxgenerations"
        const val STREETO_JENETICS_MAXFITNESS = "streeto.jenetics.maxfitness"
        const val STREETO_JENETICS_OFFSPRINGFRACTION = "streeto.jenetics.offspringfraction"
        const val STREETO_JENETICS_POPSIZE = "streeto.jenetics.popsize"
        const val STREETO_JENETICS_MAXAGE = "streeto.jenetics.maxage"
        const val STREETO_PBF_FILE = "streeto.pbf.file"
        const val STREETO_OSMDATA_FOLDER = "streeto.osmdata.folder"
        const val STREETO_NUM_CONTROLS = "streeto.num.controls"
        const val STREETO_REQUESTED_DISTANCE = "streeto.requested.distance"
    }
}